settings: &settings
  site_title: "TestLi"
  site_footer: "@2013"
  case_state_select: [['open', 0], ['dev', 1], ['done', 2]]
  case_state_view: ['open', 'dev', 'done']

  
development:
  <<: *settings
  
test:
  <<: *settings
  
production:
  <<: *settings

